=== quenthbk/cv21rest/src/main/resources/static/cv21.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://univ.fr/cv21" xmlns="http://univ.fr/cv21" elementFormDefault="unqualified" >
	<xs:simpleType name="genre">
	  	<xs:restriction base="xs:string">
	  		<xs:enumeration value="M"/>
	  		<xs:enumeration value="Mme"/>
	  	</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="tel">
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-9]{10}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="mel">
		<xs:restriction base="xs:string">
			<xs:pattern value="([0-9a-zA-Z]([-.\w]*[0-9a-zA-Z])*@([0-9a-zA-Z][-\w]*[0-9a-zA-Z]\.)+[a-zA-Z]{2,9})"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="cv21">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="identite">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="genre" type="genre"/>
							<xs:element name="nom">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="32" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="prenom">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="32" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="tel" type="tel" minOccurs="0" maxOccurs="1"/>
							<xs:element name="mel" type="mel" minOccurs="0" maxOccurs="1"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="objectif">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="stage" use="optional"/>
								<xs:attribute name="emploi" use="optional"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="prof">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="expe" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="datedeb" type="xs:date"/>
										<xs:element name="datefin" type="xs:date"/>
										<xs:element name="titre">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="128"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="competences">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="diplÃ´me" minOccurs="1" maxOccurs="5">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="date" type="xs:date"/>
										<xs:element name="titre">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="32"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="etab">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="32"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="niveau">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="I" />
												<xs:enumeration value="II" />
												<xs:enumeration value="III" />
												<xs:enumeration value="IV" />
												<xs:enumeration value="V" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
							<xs:element name="certif" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="datedeb" type="xs:date"/>
										<xs:element name="datefin" type="xs:date" minOccurs="0" maxOccurs="1"/>
										<xs:element name="titre">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="32"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="divers">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="lv" minOccurs="1" maxOccurs="5">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="lang"/>
											<xs:attribute name="cert">
												<xs:simpleType>
													<xs:restriction base="xs:string">
														<xs:enumeration value="MAT" />
														<xs:enumeration value="CLES" />
														<xs:enumeration value="TOEIC" />
													</xs:restriction>
												</xs:simpleType>
											</xs:attribute>
											<xs:attribute name="nivs" use="optional">
												<xs:simpleType>
													<xs:restriction base="xs:string">
														<xs:enumeration value="A1" />
														<xs:enumeration value="A2" />
														<xs:enumeration value="B1" />
														<xs:enumeration value="B2" />
														<xs:enumeration value="C1" />
														<xs:enumeration value="C2" />
													</xs:restriction>
												</xs:simpleType>
											</xs:attribute>
											<xs:attribute name="nivi" use="optional">
												<xs:simpleType>
													<xs:restriction base="xs:positiveInteger">
														<xs:maxInclusive value="990" />
														<xs:minInclusive value="10" />
													</xs:restriction>
												</xs:simpleType>
											</xs:attribute>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="autre" minOccurs="0" maxOccurs="3">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="titre">
												<xs:simpleType>
													<xs:restriction base="xs:string">
														<xs:maxLength value="32"/>
													</xs:restriction>
												</xs:simpleType>
											</xs:attribute>
											<xs:attribute name="comment">
												<xs:simpleType>
													<xs:restriction base="xs:string">
														<xs:maxLength value="128"/>
													</xs:restriction>
												</xs:simpleType>
											</xs:attribute>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== quenthbk/cv21rest/src/main/resources/static/cv21.tp1.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:cv21 xmlns:p="http://univ.fr/cv21" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://univ.fr/cv21 cv21.xsd ">
  <identite>
    <genre>M</genre>
    <nom>nom</nom>
    <prenom>prenom</prenom>
  </identite>
  <objectif>objectif</objectif>
  <prof>
    <expe>
      <datedeb>2001-01-01</datedeb>
      <datefin>2001-01-01</datefin>
      <titre>titre</titre>
    </expe>
  </prof>
  <competences>
    <diplôme>
      <date>2001-01-01</date>
      <titre>titre</titre>
      <etab>etab</etab>
    </diplôme>
  </competences>
  <divers>
    <lv>lv</lv>
  </divers>
</p:cv21>
